INSERT INTO catalog.feed_items (id, title, content, content_type, target_role, field_slug, summary, career_impact_score, career_impact_text, views, metadata, published_at, created_at, updated_at) VALUES
('f001', 'AlphaFold 3 Revolutionizes Drug Discovery', 'DeepMind released AlphaFold 3, capable of predicting interactions between proteins, DNA, RNA, and small molecules with unprecedented accuracy.', 'MODEL', 'STUDENT', 'medicine', 'AlphaFold 3 can now model how drugs interact with the human body at an atomic level.', 9, 'High impact: Accelerates pharmaceutical research timelines by years.', 1500, '{}', NOW(), NOW(), NOW()),
('f002', 'GitHub Copilot Enterprise Transforms Dev Teams', 'GitHub launches Copilot Enterprise, bringing AI pair programming to entire organizations with codebase-aware suggestions.', 'PRODUCT', 'STUDENT', 'engineering', 'Enterprise-grade AI coding assistant that understands your entire codebase.', 8, 'Significant: Changes how software teams collaborate and write code.', 3200, '{}', NOW(), NOW(), NOW()),
('f003', 'Midjourney v6 Achieves Photorealism', 'The latest Midjourney version produces images nearly indistinguishable from photographs, with accurate text rendering.', 'MODEL', 'STUDENT', 'art-design', 'Midjourney v6 brings photorealistic AI image generation to creative professionals.', 7, 'Transformative for graphic design, advertising, and content creation.', 4500, '{}', NOW(), NOW(), NOW()),
('f004', 'AI Legal Research: A Complete Guide', 'How law students and professionals can leverage AI tools for faster, more accurate case research and document analysis.', 'GUIDE', 'STUDENT', 'law', 'Comprehensive guide to AI-powered legal research tools and techniques.', 6, 'Moderate: AI augments but does not replace legal expertise.', 850, '{}', NOW(), NOW(), NOW()),
('f005', 'Claude 3.5 Sonnet Sets New Benchmarks', 'Anthropic releases Claude 3.5 Sonnet, outperforming GPT-4o on coding, reasoning, and multilingual tasks.', 'MODEL', 'STUDENT', 'science', 'Claude 3.5 Sonnet achieves state-of-the-art performance across academic benchmarks.', 9, 'Major advancement in AI reasoning and safety capabilities.', 5100, '{}', NOW(), NOW(), NOW()),
('f006', 'AI-Powered Crop Disease Detection', 'New deep learning models can identify 50+ crop diseases from smartphone photos with 98% accuracy.', 'ADVANCEMENT', 'STUDENT', 'agriculture', 'Smartphone-based AI helps farmers detect and treat crop diseases early.', 7, 'Reduces crop losses and pesticide use in developing regions.', 920, '{}', NOW(), NOW(), NOW()),
('f007', 'Duolingo Max: GPT-4 Powered Language Learning', 'Duolingo integrates GPT-4 for roleplay conversations and personalized explanations of mistakes.', 'PRODUCT', 'STUDENT', 'education', 'AI tutoring that adapts to each student learning style in real-time.', 8, 'Reshapes how millions learn languages with personalized AI coaching.', 2800, '{}', NOW(), NOW(), NOW()),
('f008', 'NVIDIA ACE Brings AI NPCs to Gaming', 'NVIDIA ACE technology enables game characters to have natural conversations with players using generative AI.', 'ADVANCEMENT', 'STUDENT', 'gaming', 'AI-driven NPCs that can understand context and respond naturally to player dialogue.', 8, 'Revolutionary for game design and interactive storytelling.', 3600, '{}', NOW(), NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
